-- =====================================
-- ESQUEMA DE BASE DE DATOS - GESTORPRO
-- =====================================
-- Ejecuta este script en el editor SQL de Supabase para inicializar las tablas necesarias.

-- 1. Tabla de Productos/Servicios
CREATE TABLE public.productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    unit TEXT,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    cost DECIMAL(10, 2) NOT NULL DEFAULT 0,
    stock INT NOT NULL DEFAULT 0,
    min_stock INT NOT NULL DEFAULT 0,
    barcode TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla de Clientes
CREATE TABLE public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    address TEXT,
    tags TEXT[] DEFAULT '{}',
    total_compras DECIMAL(10, 2) DEFAULT 0,
    num_compras INT DEFAULT 0,
    puntos INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabla de Empleados
CREATE TABLE public.empleados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'Personal',
    email TEXT,
    phone TEXT,
    salary DECIMAL(10, 2) DEFAULT 0,
    since DATE DEFAULT CURRENT_DATE,
    active BOOLEAN DEFAULT TRUE,
    pin TEXT DEFAULT '0000',
    ventas DECIMAL(10, 2) DEFAULT 0,
    total_vendido DECIMAL(10, 2) DEFAULT 0,
    schedule JSONB DEFAULT '{"lun": "08:00 - 18:00", "mar": "08:00 - 18:00", "mie": "08:00 - 18:00", "jue": "08:00 - 18:00", "vie": "08:00 - 18:00", "sab": "Libre", "dom": "Libre"}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabla de Citas
CREATE TABLE public.citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name TEXT NOT NULL,
    service TEXT NOT NULL,
    empleado_name TEXT NOT NULL,
    date DATE NOT NULL,
    time TEXT NOT NULL,
    duration INT DEFAULT 30,
    price DECIMAL(10, 2) DEFAULT 0,
    status TEXT DEFAULT 'pendiente', -- pendiente, completada, cancelada
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabla de Transacciones (Finanzas)
CREATE TABLE public.transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    type TEXT NOT NULL, -- ingreso, gasto
    client_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================
-- FUNCIONES DE BASE DE DATOS
-- =====================================
-- Función para decrementar stock de forma atómica y evitar race conditions durante una venta.
CREATE OR REPLACE FUNCTION public.decrement_stock(product_id BIGINT, amount INT)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.productos
  SET stock = stock - amount
  WHERE id = product_id AND stock >= amount;
END;
$$;

-- =====================================
-- DATOS DE DEMOSTRACIÓN (Opcional)
-- =====================================
-- Descomenta y ejecuta la siguiente línea si deseas poblar la base de datos con algunos productos iniciales:

-- INSERT INTO public.productos (name, category, unit, price, cost, stock, min_stock, barcode) VALUES
-- ('Shampoo Kerastase', 'Productos', 'Unidad', 25000, 15000, 10, 5, '123456789'),
-- ('Corte de Cabello', 'Servicios', 'Servicio', 15000, 0, 0, 0, null),
-- ('Esmalte de Uñas', 'Productos', 'Unidad', 5000, 3000, 4, 10, '987654321');
