-- =====================================================
-- ESQUEMA MULTI-TENANT - GESTORPRO (RegisterBox)
-- =====================================================
-- IMPORTANTE: Ejecuta este script en un proyecto de Supabase LIMPIO.
-- Si ya tienes datos en producción, consulta la sección de migración al final.
--
-- Arquitectura: Una sola DB para todos los negocios.
-- Cada fila tiene un business_id. RLS filtra automáticamente.
-- =====================================================


-- =====================================================
-- 0. EXTENSIONES
-- =====================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- =====================================================
-- 1. TABLA MAESTRA: NEGOCIOS (businesses)
-- =====================================================
-- Cada negocio que compra la app tiene una fila aquí.
CREATE TABLE public.businesses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,                          -- "Barbería Los Reyes", "Nail Salon Bella"
    slug TEXT UNIQUE NOT NULL,                   -- "barberia-los-reyes" (para URL o login)
    owner_id UUID REFERENCES auth.users(id),     -- El dueño (vinculado a Supabase Auth)
    plan TEXT DEFAULT 'basic',                   -- 'basic', 'pro', 'enterprise' (para tu modelo de precios)
    active BOOLEAN DEFAULT TRUE,                 -- Puedes desactivar un negocio si no paga
    config JSONB DEFAULT '{}'::jsonb,            -- Configuración del negocio (moneda, iva, tema, etc.)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================
-- 2. PERFILES DE USUARIO (user_profiles)
-- =====================================================
-- Vincula cada usuario de Supabase Auth a un negocio.
-- Un usuario puede ser dueño o empleado de UN negocio.
CREATE TABLE public.user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    business_id UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    role TEXT NOT NULL DEFAULT 'Personal',       -- 'Administrador', 'Gerente', 'Cajero', 'Personal'
    pin TEXT DEFAULT '0000',
    active BOOLEAN DEFAULT TRUE,
    salary DECIMAL(10, 2) DEFAULT 0,
    since DATE DEFAULT CURRENT_DATE,
    ventas DECIMAL(10, 2) DEFAULT 0,
    total_vendido DECIMAL(10, 2) DEFAULT 0,
    schedule JSONB DEFAULT '{
        "lun": "08:00 - 18:00", "mar": "08:00 - 18:00",
        "mie": "08:00 - 18:00", "jue": "08:00 - 18:00",
        "vie": "08:00 - 18:00", "sab": "Libre", "dom": "Libre"
    }'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================
-- 3. PRODUCTOS (con business_id)
-- =====================================================
CREATE TABLE public.productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    unit TEXT,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    cost DECIMAL(10, 2) NOT NULL DEFAULT 0,
    stock INT NOT NULL DEFAULT 0,
    min_stock INT NOT NULL DEFAULT 0,
    barcode TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================
-- 4. CLIENTES (con business_id)
-- =====================================================
CREATE TABLE public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    address TEXT,
    tags TEXT[] DEFAULT '{}',
    total_compras DECIMAL(10, 2) DEFAULT 0,
    num_compras INT DEFAULT 0,
    puntos INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================
-- 5. EMPLEADOS (con business_id)
-- =====================================================
-- NOTA: Si migras a Supabase Auth completo, los empleados
-- también serán user_profiles. Por ahora mantenemos esta
-- tabla para compatibilidad con el PIN system.
CREATE TABLE public.empleados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'Personal',
    email TEXT,
    phone TEXT,
    salary DECIMAL(10, 2) DEFAULT 0,
    since DATE DEFAULT CURRENT_DATE,
    active BOOLEAN DEFAULT TRUE,
    pin TEXT DEFAULT '0000',
    ventas DECIMAL(10, 2) DEFAULT 0,
    total_vendido DECIMAL(10, 2) DEFAULT 0,
    schedule JSONB DEFAULT '{
        "lun": "08:00 - 18:00", "mar": "08:00 - 18:00",
        "mie": "08:00 - 18:00", "jue": "08:00 - 18:00",
        "vie": "08:00 - 18:00", "sab": "Libre", "dom": "Libre"
    }'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================
-- 6. CITAS (con business_id)
-- =====================================================
CREATE TABLE public.citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    client_name TEXT NOT NULL,
    service TEXT NOT NULL,
    empleado_name TEXT NOT NULL,
    date DATE NOT NULL,
    time TEXT NOT NULL,
    duration INT DEFAULT 30,
    price DECIMAL(10, 2) DEFAULT 0,
    status TEXT DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================
-- 7. TRANSACCIONES (con business_id)
-- =====================================================
CREATE TABLE public.transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    type TEXT NOT NULL, -- 'ingreso', 'gasto'
    client_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================
-- 8. HORARIOS DE EMPLEADOS (con business_id)
-- =====================================================
CREATE TABLE public.horarios_empleados (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    business_id UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    empleado_id BIGINT NOT NULL REFERENCES public.empleados(id) ON DELETE CASCADE,
    dia_semana TEXT NOT NULL CHECK (dia_semana IN ('lun', 'mar', 'mie', 'jue', 'vie', 'sab', 'dom')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (empleado_id, dia_semana)
);


-- =====================================================
-- ÍNDICES (rendimiento)
-- =====================================================
CREATE INDEX idx_productos_business ON public.productos(business_id);
CREATE INDEX idx_clientes_business ON public.clientes(business_id);
CREATE INDEX idx_empleados_business ON public.empleados(business_id);
CREATE INDEX idx_citas_business ON public.citas(business_id);
CREATE INDEX idx_transacciones_business ON public.transacciones(business_id);
CREATE INDEX idx_horarios_business ON public.horarios_empleados(business_id);
CREATE INDEX idx_user_profiles_business ON public.user_profiles(business_id);


-- =====================================================
-- FUNCIÓN HELPER: obtener business_id del usuario actual
-- =====================================================
-- Cada vez que un usuario hace un query, esta función
-- devuelve el business_id de su perfil.
CREATE OR REPLACE FUNCTION public.get_my_business_id()
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT business_id
  FROM public.user_profiles
  WHERE id = auth.uid()
$$;


-- =====================================================
-- FUNCIÓN: decrementar stock (actualizada)
-- =====================================================
CREATE OR REPLACE FUNCTION public.decrement_stock(product_id BIGINT, amount INT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.productos
  SET stock = stock - amount
  WHERE id = product_id
    AND stock >= amount
    AND business_id = public.get_my_business_id();
END;
$$;


-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================
-- Esto es lo que hace que cada negocio SOLO vea sus datos.
-- Sin esto, cualquier usuario podría ver todo.

-- Habilitar RLS en cada tabla
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.empleados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.citas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transacciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.horarios_empleados ENABLE ROW LEVEL SECURITY;

-- BUSINESSES: solo ver tu propio negocio
CREATE POLICY "businesses_select" ON public.businesses
    FOR SELECT USING (
        id = public.get_my_business_id()
        OR owner_id = auth.uid()
    );

CREATE POLICY "businesses_update" ON public.businesses
    FOR UPDATE USING (owner_id = auth.uid());

-- USER_PROFILES: ver perfiles de tu negocio
CREATE POLICY "profiles_select" ON public.user_profiles
    FOR SELECT USING (business_id = public.get_my_business_id());

CREATE POLICY "profiles_self_update" ON public.user_profiles
    FOR UPDATE USING (id = auth.uid());

-- PRODUCTOS: CRUD solo para tu negocio
CREATE POLICY "productos_select" ON public.productos
    FOR SELECT USING (business_id = public.get_my_business_id());

CREATE POLICY "productos_insert" ON public.productos
    FOR INSERT WITH CHECK (business_id = public.get_my_business_id());

CREATE POLICY "productos_update" ON public.productos
    FOR UPDATE USING (business_id = public.get_my_business_id());

CREATE POLICY "productos_delete" ON public.productos
    FOR DELETE USING (business_id = public.get_my_business_id());

-- CLIENTES: CRUD solo para tu negocio
CREATE POLICY "clientes_select" ON public.clientes
    FOR SELECT USING (business_id = public.get_my_business_id());

CREATE POLICY "clientes_insert" ON public.clientes
    FOR INSERT WITH CHECK (business_id = public.get_my_business_id());

CREATE POLICY "clientes_update" ON public.clientes
    FOR UPDATE USING (business_id = public.get_my_business_id());

CREATE POLICY "clientes_delete" ON public.clientes
    FOR DELETE USING (business_id = public.get_my_business_id());

-- EMPLEADOS: CRUD solo para tu negocio
CREATE POLICY "empleados_select" ON public.empleados
    FOR SELECT USING (business_id = public.get_my_business_id());

CREATE POLICY "empleados_insert" ON public.empleados
    FOR INSERT WITH CHECK (business_id = public.get_my_business_id());

CREATE POLICY "empleados_update" ON public.empleados
    FOR UPDATE USING (business_id = public.get_my_business_id());

CREATE POLICY "empleados_delete" ON public.empleados
    FOR DELETE USING (business_id = public.get_my_business_id());

-- CITAS: CRUD solo para tu negocio
CREATE POLICY "citas_select" ON public.citas
    FOR SELECT USING (business_id = public.get_my_business_id());

CREATE POLICY "citas_insert" ON public.citas
    FOR INSERT WITH CHECK (business_id = public.get_my_business_id());

CREATE POLICY "citas_update" ON public.citas
    FOR UPDATE USING (business_id = public.get_my_business_id());

CREATE POLICY "citas_delete" ON public.citas
    FOR DELETE USING (business_id = public.get_my_business_id());

-- TRANSACCIONES: CRUD solo para tu negocio
CREATE POLICY "transacciones_select" ON public.transacciones
    FOR SELECT USING (business_id = public.get_my_business_id());

CREATE POLICY "transacciones_insert" ON public.transacciones
    FOR INSERT WITH CHECK (business_id = public.get_my_business_id());

CREATE POLICY "transacciones_update" ON public.transacciones
    FOR UPDATE USING (business_id = public.get_my_business_id());

CREATE POLICY "transacciones_delete" ON public.transacciones
    FOR DELETE USING (business_id = public.get_my_business_id());

-- HORARIOS: CRUD solo para tu negocio
CREATE POLICY "horarios_select" ON public.horarios_empleados
    FOR SELECT USING (business_id = public.get_my_business_id());

CREATE POLICY "horarios_insert" ON public.horarios_empleados
    FOR INSERT WITH CHECK (business_id = public.get_my_business_id());

CREATE POLICY "horarios_update" ON public.horarios_empleados
    FOR UPDATE USING (business_id = public.get_my_business_id());

CREATE POLICY "horarios_delete" ON public.horarios_empleados
    FOR DELETE USING (business_id = public.get_my_business_id());


-- =====================================================
-- REALTIME: habilitar para todas las tablas
-- =====================================================
ALTER TABLE public.productos REPLICA IDENTITY FULL;
ALTER TABLE public.clientes REPLICA IDENTITY FULL;
ALTER TABLE public.empleados REPLICA IDENTITY FULL;
ALTER TABLE public.citas REPLICA IDENTITY FULL;
ALTER TABLE public.transacciones REPLICA IDENTITY FULL;

ALTER PUBLICATION supabase_realtime ADD TABLE productos;
ALTER PUBLICATION supabase_realtime ADD TABLE clientes;
ALTER PUBLICATION supabase_realtime ADD TABLE empleados;
ALTER PUBLICATION supabase_realtime ADD TABLE citas;
ALTER PUBLICATION supabase_realtime ADD TABLE transacciones;


-- =====================================================
-- TRIGGER: crear perfil automáticamente al registrarse
-- =====================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_profiles (id, business_id, name, email, role)
  VALUES (
    NEW.id,
    (NEW.raw_user_meta_data ->> 'business_id')::uuid,
    COALESCE(NEW.raw_user_meta_data ->> 'name', 'Usuario'),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'role', 'Administrador')
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();